import type { MigrationFormValues } from "./formModel";

export const defaultMigrationForm: MigrationFormValues = {
  request_id: "",
  source: {
    oracle_version: "19c",
    deployment_type: "ON_PREM",
    platform: "Linux",
    storage_type: "ASM",
    database_size_gb: 0,
    largest_table_gb: 0,
    daily_change_rate_gb: 0,
    peak_redo_mb_per_sec: 0,
    character_set: "AL32UTF8",
    tde_enabled: false,
    rac_enabled: false,
    dataguard_enabled: false,
    archivelog_enabled: true,
  },
  target: {
    oracle_version: "19c",
    deployment_type: "ON_PREM",
    platform: "Linux",
    storage_type: "ASM",
    target_is_exadata: false,
    same_endian: true,
  },
  scope: {
    migration_scope: "FULL_DATABASE",
    schema_count: 1,
    schema_names: "",
    need_schema_remap: false,
    need_tablespace_remap: false,
    need_reorg: false,
    subset_only: false,
  },
  business: {
    downtime_window_minutes: 240,
    fallback_required: true,
    near_zero_downtime_required: false,
    regulated_workload: false,
  },
  connectivity: {
    network_bandwidth_mbps: 1000,
    direct_host_connectivity: true,
    shared_storage_available: false,
  },
  features: {
    need_version_upgrade: false,
    need_cross_platform_move: false,
    need_non_cdb_to_pdb_conversion: false,
    goldengate_license_available: false,
    zdm_supported_target: false,
  },
  metadata_collection: {
    enabled: false,
    prefer_collected_values: true,
    source_connection: {
      host: "",
      port: 1521,
      service_name: "",
      username: "",
      password: "",
      mode: "thin",
      sysdba: false,
      wallet_location: "",
    },
    target_connection: {
      host: "",
      port: 1521,
      service_name: "",
      username: "",
      password: "",
      mode: "thin",
      sysdba: false,
      wallet_location: "",
    },
  },
};
